/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowToFoldRouteImport } from './routes/how-to-fold'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDownloadPdfRouteImport } from './routes/api/download-pdf'

const HowToFoldRoute = HowToFoldRouteImport.update({
  id: '/how-to-fold',
  path: '/how-to-fold',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadPdfRoute = ApiDownloadPdfRouteImport.update({
  id: '/api/download-pdf',
  path: '/api/download-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-to-fold': typeof HowToFoldRoute
  '/api/download-pdf': typeof ApiDownloadPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-to-fold': typeof HowToFoldRoute
  '/api/download-pdf': typeof ApiDownloadPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-to-fold': typeof HowToFoldRoute
  '/api/download-pdf': typeof ApiDownloadPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/how-to-fold' | '/api/download-pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/how-to-fold' | '/api/download-pdf'
  id: '__root__' | '/' | '/about' | '/how-to-fold' | '/api/download-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HowToFoldRoute: typeof HowToFoldRoute
  ApiDownloadPdfRoute: typeof ApiDownloadPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-to-fold': {
      id: '/how-to-fold'
      path: '/how-to-fold'
      fullPath: '/how-to-fold'
      preLoaderRoute: typeof HowToFoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-pdf': {
      id: '/api/download-pdf'
      path: '/api/download-pdf'
      fullPath: '/api/download-pdf'
      preLoaderRoute: typeof ApiDownloadPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HowToFoldRoute: HowToFoldRoute,
  ApiDownloadPdfRoute: ApiDownloadPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
